GET http://localhost:8080/api

###

POST http://localhost:8080/api/login

###

POST http://localhost:8080/api/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6Im1heWJhdGNoIiwiZW1haWwiOiJtYXkyMUBjb2RpbmduaW5qYXMuY29tIn0sImlhdCI6MTYzOTIzNTAwNSwiZXhwIjoxNjM5MjM1MDY1fQ.HcLXcECe5n6wGE6PGqwW_QqFGF4zb2te1svxnmt9ZTg